name: Docker
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up docker build
        uses: docker/setup-buildx-action@v3.12.0
      
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          registry: # optional
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.SECRET_DOCKER }}
          logout: true
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/app:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/app:cache,mode=max
          # Opcionais comentados abaixo:
          # add-hosts: 
          # allow: 
          # annotations: 
          # attests: 
          # build-args: 
          # build-contexts: 
          # builder: 
          # call: 
          # cgroup-parent: 
          # labels: 
          # load: false
          # network: 
          # no-cache: false
          # no-cache-filters: 
          # outputs: 
          # provenance: 
          # pull: false
          # sbom: 
          # secrets: 
          # secret-envs: 
          # secret-files: 
          # shm-size: 
          # ssh: 
          # target: 
          # ulimit: 
          # github-token: ${{ github.token }}
